In [1]:
import numpy as np
from datetime import datetime
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
file_path = '../data/raw/E-mini_ES_hist.xlsx'
years = range(1, 7)
months = ['H', 'M', 'U', 'Z']

contracts = [f'ES{m}{y}' for y in years for m in months]

end_contracts = 'ESH6'

contracts = contracts[:contracts.index(end_contracts)+1]
print(contracts)

['ESH1', 'ESM1', 'ESU1', 'ESZ1', 'ESH2', 'ESM2', 'ESU2', 'ESZ2', 'ESH3', 'ESM3', 'ESU3', 'ESZ3', 'ESH4', 'ESM4', 'ESU4', 'ESZ4', 'ESH5', 'ESM5', 'ESU5', 'ESZ5', 'ESH6']

In [3]:
all_contracts = {}
for contract in contracts:
    df_raw = pd.read_excel(file_path, sheet_name=contract)
    price_df = df_raw[['Date', 'Last Price']].copy()
    volume_df = df_raw[['Date.1', 'Volume']].copy().rename(columns={'Date.1' : 'Date'})

    price_df['Date'] = pd.to_datetime(price_df['Date'])
    volume_df['Date'] = pd.to_datetime(volume_df['Date'])
    price_df = price_df.dropna(subset=['Date'])
    volume_df = volume_df.dropna(subset=['Date'])
    price_df = price_df.set_index('Date')
    volume_df = volume_df.set_index('Date')
    price_df = price_df.sort_index(ascending=True)
    volume_df = volume_df.sort_index(ascending=True)

    df_clean = pd.concat([price_df, volume_df], axis=1)
    all_contracts[contract] = df_clean
    print(f'{contract} cleaned')
    print(df_clean)

ESH1 cleaned
            Last Price     Volume
Date
2020-03-09   2730.5000        NaN
2020-03-10   2840.0000        NaN
2020-03-11   2691.2500        NaN
2020-03-12   2433.0000        NaN
2020-03-13   2658.0000        NaN
...                ...        ...
2021-03-15   3967.6001  1295099.0
2021-03-16   3962.3999   887247.0
2021-03-17   3974.0000   520411.0
2021-03-18   3916.3999   335435.0
2021-03-19   3912.6201    38644.0

[261 rows x 2 columns]
ESM1 cleaned
            Last Price     Volume
Date
2020-04-23   2754.5000        NaN
2020-04-24   2800.0000        NaN
2020-04-27   2841.0000        NaN
2020-04-28   2838.2500        NaN
2020-04-29   2912.0000        NaN
...                ...        ...
2021-06-14   4254.7002  1116773.0
2021-06-15   4246.6001   981189.0
2021-06-16   4223.1001   511740.0
2021-06-17   4222.2002   326193.0
2021-06-18   4187.2500    35117.0

[293 rows x 2 columns]
ESU1 cleaned
            Last Price     Volume
Date
2020-06-08   3183.2500        NaN
2020-06-09   3163.7500        NaN
2020-06-10   3146.0000        NaN
2020-06-11   2969.5000        NaN
2020-06-12   2995.0000        NaN
...                ...        ...
2021-09-13   4468.8999  1534719.0
2021-09-14   4444.6001   893788.0
2021-09-15   4481.7002   518985.0
2021-09-16   4474.2998   268026.0
2021-09-17   4464.3301    24266.0

[325 rows x 2 columns]
ESZ1 cleaned
            Last Price     Volume
Date
2020-09-18     3274.75        NaN
2020-09-21     3233.00        NaN
2020-09-22     3258.25        NaN
2020-09-23     3190.50        NaN
2020-09-24     3196.50        NaN
...                ...        ...
2021-12-13     4668.75  1605196.0
2021-12-14     4637.00  1211592.0
2021-12-15     4709.50   673190.0
2021-12-16     4668.75   435986.0
2021-12-17     4636.46    34916.0

[317 rows x 2 columns]
ESH2 cleaned
            Last Price     Volume
Date
2020-12-07   3631.2500        NaN
2020-12-08   3641.7500        NaN
2020-12-09   3616.5000        NaN
2020-12-10   3608.5000        NaN
2020-12-11   3603.0000        NaN
...                ...        ...
2022-03-14   4172.0000  1438651.0
2022-03-15   4262.0000  1085846.0
2022-03-16   4358.0000   722600.0
2022-03-17   4410.2500   434642.0
2022-03-18   4409.3501    33552.0

[323 rows x 2 columns]
ESM2 cleaned
            Last Price     Volume
Date
2021-03-08   3759.6001        NaN
2021-03-09   3813.7000        NaN
2021-03-10   3834.1001        NaN
2021-03-11   3875.2000        NaN
2021-03-12   3878.6001        NaN
...                ...        ...
2022-06-13   3750.5000  2155159.0
2022-06-14   3736.7500  1341257.0
2022-06-15   3789.2500   777545.0
2022-06-16   3668.2500   544027.0
2022-06-17   3663.7600    40397.0

[325 rows x 2 columns]
ESU2 cleaned
            Last Price     Volume
Date
2021-06-04   4180.1001        NaN
2021-06-07   4177.7002        NaN
2021-06-08   4177.7002        NaN
2021-06-09   4170.8999        NaN
2021-06-10   4190.7998        NaN
...                ...        ...
2022-09-12   4110.7500  1718859.0
2022-09-13   3931.2500  1418271.0
2022-09-14   3947.5000   662596.0
2022-09-15   3902.0000   438921.0
2022-09-16   3871.2400    44853.0

[325 rows x 2 columns]
ESZ2 cleaned
            Last Price     Volume
Date
2021-06-04   4170.2998        NaN
2021-06-07   4167.8999        NaN
2021-06-08   4167.8999        NaN
2021-06-09   4161.1001        NaN
2021-06-10   4181.1001        NaN
...                ...        ...
2022-12-12   3991.7500  1619977.0
2022-12-13   4022.2500  1419560.0
2022-12-14   3998.0000   712439.0
2022-12-15   3897.0000   560669.0
2022-12-16   3871.4700    41155.0

[389 rows x 2 columns]
ESH3 cleaned
            Last Price     Volume
Date
2021-06-04   4160.6001        NaN
2021-06-07   4158.2002        NaN
2021-06-08   4158.2002        NaN
2021-06-09   4151.3999        NaN
2021-06-10   4171.2998        NaN
...                ...        ...
2023-03-13   3856.7500  2750477.0
2023-03-14   3920.5000  1606509.0
2023-03-15   3892.7500   833643.0
2023-03-16   3960.5000   466914.0
2023-03-17   3957.0500    38637.0

[450 rows x 2 columns]
ESM3 cleaned
            Last Price     Volume
Date
2021-06-04   4145.8999        NaN
2021-06-07   4148.3999        NaN
2021-06-08   4148.3999        NaN
2021-06-09   4141.7002        NaN
2021-06-10   4161.5000        NaN
...                ...        ...
2023-06-12   4342.7500  1665175.0
2023-06-13   4371.7500  1317118.0
2023-06-14   4374.2500   758316.0
2023-06-15   4426.5000   486414.0
2023-06-16   4453.3501    39140.0

[514 rows x 2 columns]
ESU3 cleaned
            Last Price     Volume
Date
2021-06-17   4134.7002        NaN
2021-06-18   4087.8000        NaN
2021-06-21   4146.8999        NaN
2021-06-22   4167.7002        NaN
2021-06-23   4173.2002        NaN
...                ...        ...
2023-09-11   4490.2500  1714266.0
2023-09-12   4465.0000  1153961.0
2023-09-13   4468.7500   690872.0
2023-09-14   4506.0000   454906.0
2023-09-15   4491.7202    44159.0

[567 rows x 2 columns]
ESZ3 cleaned
            Last Price     Volume
Date
2021-06-04   4131.2998        NaN
2021-06-07   4128.8999        NaN
2021-06-08   4146.3999        NaN
2021-06-09   4139.7002        NaN
2021-06-10   4159.5000        NaN
...                ...        ...
2023-12-11   4626.0000  1663229.0
2023-12-12   4645.7500  1052077.0
2023-12-13   4708.2500   739684.0
2023-12-14   4721.7500   560819.0
2023-12-15   4694.2700    36814.0

[640 rows x 2 columns]
ESH4 cleaned
            Last Price     Volume
Date
2021-12-15   4710.0000        NaN
2021-12-16   4664.5000        NaN
2021-12-17   4614.2500        NaN
2021-12-20   4561.7500        NaN
2021-12-21   4641.7500        NaN
...                ...        ...
2024-03-11   5123.0000  1840000.0
2024-03-12   5177.2500  1211911.0
2024-03-13   5168.0000   540170.0
2024-03-14   5153.7500   476074.0
2024-03-15   5101.6699    41694.0

[566 rows x 2 columns]
ESM4 cleaned
            Last Price     Volume
Date
2022-03-18   4565.0000        NaN
2022-03-21   4576.0000        NaN
2022-03-22   4641.0000        NaN
2022-03-23   4571.0000        NaN
2022-03-24   4639.0000        NaN
...                ...        ...
2024-06-14   5437.5000  1789793.0
2024-06-17   5478.5000  1589643.0
2024-06-18   5491.0000   820053.0
2024-06-20   5476.7500   571332.0
2024-06-21   5471.8901    24598.0

[569 rows x 2 columns]
ESU4 cleaned
            Last Price     Volume
Date
2022-06-16   3870.0000        NaN
2022-06-17   3857.0000        NaN
2022-06-21   3952.0000        NaN
2022-06-22   3931.0000        NaN
2022-06-23   3967.0000        NaN
...                ...        ...
2024-09-16   5638.0000  1588010.0
2024-09-17   5639.0000  1056184.0
2024-09-18   5620.7500   605651.0
2024-09-19   5717.7500   461433.0
2024-09-20   5699.9902    27392.0

[570 rows x 2 columns]
ESZ4 cleaned
            Last Price     Volume
Date
2021-06-04   4091.5000        NaN
2021-06-07   4089.2000        NaN
2021-06-08   4136.3999        NaN
2021-06-09   4129.7002        NaN
2021-06-10   4149.5000        NaN
...                ...        ...
2024-12-16   6080.5000  1612199.0
2024-12-17   6053.7500  1113325.0
2024-12-18   5872.2500   847452.0
2024-12-19   5868.7500   532081.0
2024-12-20   5840.2598    43428.0

[895 rows x 2 columns]
ESH5 cleaned
            Last Price     Volume
Date
2022-12-14     4273.00        NaN
2022-12-15     4160.00        NaN
2022-12-16     4110.00        NaN
2022-12-19     4076.00        NaN
2022-12-20     4080.00        NaN
...                ...        ...
2025-03-17     5680.25  2086734.0
2025-03-18     5618.00  1111733.0
2025-03-19     5678.50   704394.0
2025-03-20     5662.50   412785.0
2025-03-21     5617.80    34431.0

[570 rows x 2 columns]
ESM5 cleaned
            Last Price     Volume
Date
2023-03-16     4231.00        NaN
2023-03-17     4181.00        NaN
2023-03-20     4211.00        NaN
2023-03-21     4271.00        NaN
2023-03-22     4206.00        NaN
...                ...        ...
2025-06-13     5979.25  2162167.0
2025-06-16     6035.75  1744867.0
2025-06-17     5985.00   870571.0
2025-06-18     5981.50   453191.0
2025-06-20     6010.21    71814.0

[570 rows x 2 columns]
ESU5 cleaned
            Last Price     Volume
Date
2023-06-15     4735.00        NaN
2023-06-16     4723.00        NaN
2023-06-20     4704.00        NaN
2023-06-21     4678.00        NaN
2023-06-22     4693.00        NaN
...                ...        ...
2025-09-15     6621.50  1539732.0
2025-09-16     6610.75   837034.0
2025-09-17     6601.25   560841.0
2025-09-18     6635.00   339967.0
2025-09-19     6658.77    19794.0

[569 rows x 2 columns]
ESZ5 cleaned
            Last Price     Volume
Date
2021-06-04     4052.50        NaN
2021-06-07     4050.20        NaN
2021-06-08     4144.80        NaN
2021-06-09     4138.10        NaN
2021-06-10     4157.90        NaN
...                ...        ...
2025-12-15     6823.00  1771047.0
2025-12-16     6801.00  1070240.0
2025-12-17     6726.50   590558.0
2025-12-18     6778.25   416394.0
2025-12-19     6796.54    22274.0

[1145 rows x 2 columns]
ESH6 cleaned
            Last Price   Volume
Date
2023-08-17     4762.00      NaN
2023-08-18     4759.00      NaN
2023-08-21     4790.00      NaN
2023-08-22     4777.00      NaN
2023-08-23     4825.00      NaN
...                ...      ...
2026-03-20     6594.63  26273.0
2026-03-23         NaN      NaN
2026-03-24         NaN      NaN
2026-03-25         NaN      NaN
2026-03-26         NaN      NaN

[659 rows x 2 columns]

In [4]:
E_mini_hist = pd.concat(all_contracts, axis=1, sort=True)
E_mini_hist = E_mini_hist.swaplevel(axis=1)
E_mini_hist

,Last Price,Volume,Last Price,Volume,Last Price,Volume,Last Price,Volume,Last Price,Volume,...,Last Price,Volume,Last Price,Volume,Last Price,Volume,Last Price,Volume,Last Price,Volume
,ESH1,ESH1,ESM1,ESM1,ESU1,ESU1,ESZ1,ESZ1,ESH2,ESH2,...,ESH5,ESH5,ESM5,ESM5,ESU5,ESU5,ESZ5,ESZ5,ESH6,ESH6
Date,,,,,,,,,,,,,,,,,,,,,
2020-03-09,2730.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-10,2840.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-11,2691.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-12,2433.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-13,2658.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6594.63,26273.0
2026-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
fut_price = E_mini_hist['Last Price']
fut_price

,ESH1,ESM1,ESU1,ESZ1,ESH2,ESM2,ESU2,ESZ2,ESH3,ESM3,...,ESZ3,ESH4,ESM4,ESU4,ESZ4,ESH5,ESM5,ESU5,ESZ5,ESH6
Date,,,,,,,,,,,,,,,,,,,,,
2020-03-09,2730.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-10,2840.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-11,2691.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-12,2433.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-13,2658.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6594.63
2026-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
fut_price.to_excel('../data/processed/E-mini_expired_price.xlsx')