In [5]:
import numpy as np
from datetime import datetime
import pandas as pd
import yfinance as yf

In [7]:
# ticker = "^GSPC"
tickers_members = pd.read_excel('../data/raw/spx_members.xlsx')
tickers_members

     Unnamed: 0 Unnamed: 1 tickers
0           NaN       A UN       A
1           0.0    AAPL UW    AAPL
2           1.0    ABBV UN    ABBV
3           2.0    ABNB UW    ABNB
4           3.0     ABT UN     ABT
..          ...        ...     ...
498       497.0     XYZ UN     XYZ
499       498.0     YUM UN     YUM
500       499.0     ZBH UN     ZBH
501       500.0    ZBRA UW    ZBRA
502       501.0     ZTS UN     ZTS

[503 rows x 3 columns]

In [21]:
tickers = tickers_members[['tickers']].values
tickers = tickers.flatten().tolist()
print(tickers)

['A', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APO', 'APP', 'APTV', 'ARE', 'ARES', 'ATO', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXON', 'AXP', 'AZO', 'BA', 'BAC', 'BALL', 'BAX', 'BBY', 'BDX', 'BEN', 'BF/B', 'BG', 'BIIB', 'BK', 'BKNG', 'BKR', 'BLDR', 'BLK', 'BMY', 'BR', 'BRK/B', 'BRO', 'BSX', 'BX', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CCI', 'CCL', 'CDNS', 'CDW', 'CEG', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CIEN', 'CINF', 'CL', 'CLX', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COHR', 'COIN', 'COO', 'COP', 'COR', 'COST', 'CPAY', 'CPB', 'CPRT', 'CPT', 'CRH', 'CRL', 'CRM', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTRA', 'CTSH', 'CTVA', 'CVNA', 'CVS', 'CVX', 'D', 'DAL', 'DASH', 'DD', 'DDOG', 'DE', 'DECK', 'DELL', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DLR', 'DLTR', 'DOC', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EG', 'EIX', 'EL', 'ELV', 'EME', 'EMR', 'EOG', 'EPAM', 'EQIX', 'EQR', 'EQT', 'ERIE', 'ES', 'ESS', 'ETN', 'ETR', 'EVRG', 'EW', 'EXC', 'EXE', 'EXPD', 'EXPE', 'EXR', 'F', 'FANG', 'FAST', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FICO', 'FIS', 'FISV', 'FITB', 'FIX', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV', 'GD', 'GDDY', 'GE', 'GEHC', 'GEN', 'GEV', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW', 'HAL', 'HAS', 'HBAN', 'HCA', 'HD', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HOOD', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HST', 'HSY', 'HUBB', 'HUM', 'HWM', 'IBKR', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'INCY', 'INTC', 'INTU', 'INVH', 'IP', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JBL', 'JCI', 'JKHY', 'JNJ', 'JPM', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KKR', 'KLAC', 'KMB', 'KMI', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LH', 'LHX', 'LII', 'LIN', 'LITE', 'LLY', 'LMT', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUV', 'LVS', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'META', 'MGM', 'MKC', 'MLM', 'MMM', 'MNST', 'MO', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRSH', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWS', 'NWSA', 'NXPI', 'O', 'ODFL', 'OKE', 'OMC', 'ON', 'ORCL', 'ORLY', 'OTIS', 'OXY', 'PANW', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PLD', 'PLTR', 'PM', 'PNC', 'PNR', 'PNW', 'PODD', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSKY', 'PSX', 'PTC', 'PWR', 'PYPL', 'Q', 'QCOM', 'RCL', 'REG', 'REGN', 'RF', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'RVTY', 'SATS', 'SBAC', 'SBUX', 'SCHW', 'SHW', 'SJM', 'SLB', 'SMCI', 'SNA', 'SNDK', 'SNPS', 'SO', 'SOLV', 'SPG', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'STX', 'STZ', 'SW', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TKO', 'TMO', 'TMUS', 'TPL', 'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTD', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UBER', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VICI', 'VLO', 'VLTO', 'VMC', 'VRSK', 'VRSN', 'VRT', 'VRTX', 'VST', 'VTR', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBD', 'WDAY', 'WDC', 'WEC', 'WELL', 'WFC', 'WM', 'WMB', 'WMT', 'WRB', 'WSM', 'WST', 'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM', 'ZBH', 'ZBRA', 'ZTS']

In [25]:
end_date = datetime.today()
start_date = end_date - pd.DateOffset(years=10)

data = yf.download(
    '^SPX',
    start=start_date,
    end=end_date,
    auto_adjust=True
)

[*********************100%***********************]  1 of 1 completed

In [26]:
data.tail()

Price             Close         High          Low         Open      Volume
Ticker             ^SPX         ^SPX         ^SPX         ^SPX        ^SPX
Date
2026-03-31  6528.520020  6539.049805  6395.879883  6395.879883  6396100000
2026-04-01  6575.319824  6609.669922  6554.290039  6556.560059  5637260000
2026-04-02  6582.689941  6601.910156  6474.939941  6512.609863  4740740000
2026-04-06  6611.830078  6618.129883  6579.720215  6587.660156  3906440000
2026-04-07  6616.850098  6618.259766  6534.549805  6601.930176  4555680000

In [24]:
data['Open'].to_excel("open.xlsx")
data['High'].to_excel("high.xlsx")
data['Low'].to_excel("low.xlsx")
data['Close'].to_excel("close.xlsx")
data['Volume'].to_excel("volume.xlsx")

In [27]:
# data.columns.get_level_values(0).unique()
prices = data["Close"].dropna(axis=1)

In [8]:
# volume = data["Volume"].dropna(axis=1)
# volume

Ticker,AAPL,ABBV,ABT,ACN,ADBE,AIG,AMD,AMGN,AMZN,AXP,...,TXN,UNH,UNP,UPS,USB,V,VZ,WFC,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-03-30,182404400,3650300,3433000,3182300,6797200,8375500,14945900,2324500,77810000,5103200,...,5026700,2578500,3145900,2277700,6293200,9691900,14528300,16794200,21625500,10807000
2016-03-31,103553600,4930300,5168400,2740600,6561400,8315000,9071500,2799600,53636000,6310200,...,5410400,3181800,5116800,3303900,6579000,7490800,12428600,16397600,18850500,13896900
2016-04-01,103496000,4525700,3972900,2019200,3981300,6461700,8257700,3972200,58348000,4167500,...,4542600,3901700,4232900,2764400,5211800,10183400,13807100,14321400,19807200,12235300
2016-04-04,149424800,8108100,4407800,2231900,2398300,5308800,5591100,2314200,49416000,3367300,...,3423700,2812400,3464800,2796200,4685300,6905800,11402700,12110200,20470200,8050200
2016-04-05,106314800,6779400,6582700,2069700,2472600,6605600,9640200,2604600,46178000,4640000,...,4455900,4440000,3614300,2178700,6223900,6012000,12979100,18297700,17337000,10446800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-23,40546100,7419900,8227800,4827900,4080500,2658600,31857800,2368700,44277400,4319800,...,7452800,10424200,2434100,7412100,12235400,7824500,26390300,15320800,22181500,25021300
2026-03-24,45152300,6990500,11794300,5113700,6268300,5758800,27258800,2336700,35351400,3639100,...,7015200,5911700,2481600,4249800,13434600,5375900,20264600,19134300,17269600,26131800
2026-03-25,28476700,6000100,6377000,4371200,5441600,5504100,48518300,1831900,36388800,2823800,...,4505800,8121200,2800600,3351000,8957400,6280900,21920200,17213400,16597300,17192300
2026-03-26,41796700,4576300,6212300,4916500,4715300,3549000,49213000,2044800,46746000,2887500,...,6314400,6218800,2225700,3790900,7317100,7652700,24423300,15430500,16442500,18625200
2026-03-27,47842500,5653100,10915000,4890100,4425100,4081200,29111300,2274800,55855900,2750300,...,5792700,10720100,2675000,5909500,10774300,9971900,26270000,13673200,16537300,30296400

In [30]:
prices.to_excel("../data/s&p500_close.xlsx")
# volume.to_csv("spx100_volume.csv")